# Generated by Django 2.1.2 on 2018-10-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panic', '0002_auto_20181017_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
