# Generated by Django 2.1.2 on 2018-10-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panic', '0005_remove_account_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
