# Generated by Django 2.1.2 on 2018-10-18 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panic', '0006_location_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panic.Account'),
        ),
    ]
