# Generated by Django 2.1.2 on 2018-10-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panic', '0009_auto_20181022_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paniclocation',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
