# Generated by Django 2.1.2 on 2018-10-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panic', '0012_disasterarea_disaster_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterarea',
            name='lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disasterarea',
            name='lng',
            field=models.IntegerField(default=0),
        ),
    ]
