# Generated by Django 2.1.2 on 2018-10-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panic', '0013_auto_20181026_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panic_time', models.IntegerField(default=0)),
                ('panic_limit', models.IntegerField(default=0)),
            ],
        ),
    ]
